In [2]:
import numpy as np

In [4]:
alist = [1, 2, 3, 4, 5]
narray = np.array([1, 2, 3, 4])

In [6]:
print(alist)
print(narray)
print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [7]:
print(narray + narray)
print(alist + alist)

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [8]:
print(narray * 3)
print(alist * 3)

[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [9]:
npmatrix1 = np.array([narray, narray, narray]) # Matrix initialized with NumPy arrays
npmatrix2 = np.array([alist, alist, alist]) # Matrix initialized with lists
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray]) # Matrix initialized with both types
print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [10]:
okmatrix = np.array([[1, 2], [3, 4]])
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [11]:
badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]])
print(badmatrix)
print(badmatrix * 2)

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


C:\Users\dell\AppData\Local\Temp/ipykernel_13932/2051504424.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]])


In [12]:
result = okmatrix * 2 + 1
print(result)

[[3 5]
 [7 9]]


In [13]:
result1 = okmatrix + okmatrix
print(result1)
result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [14]:
result = okmatrix * okmatrix
print(result)

[[ 1  4]
 [ 9 16]]


In [15]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]])
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


In [16]:
nparray = np.array([1, 2, 3, 4]) # Define an array
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[1 2 3 4]
Transposed array
[1 2 3 4]


In [17]:
nparray = np.array([[1, 2, 3, 4]])
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


In [18]:
nparray1 = np.array([1, 2, 3, 4])
norm1 = np.linalg.norm(nparray1)
nparray2 = np.array([[1, 2], [3, 4]])
norm2 = np.linalg.norm(nparray2)
print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


In [19]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]])
normByCols = np.linalg.norm(nparray2, axis=0)
normByRows = np.linalg.norm(nparray2, axis=1)
print(normByCols)
print(normByRows)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [21]:
nparray1 = np.array([0, 1, 2, 3]) # Define an array
nparray2 = np.array([4, 5, 6, 7]) # Define an array
flavor1 = np.dot(nparray1, nparray2) # Way-1
print(flavor1)
flavor2 = np.sum(nparray1 * nparray2) # Way-2
print(flavor2)
flavor3 = nparray1 @ nparray2 # Way-3
print(flavor3)
# As you never should do: #Way-4
flavor4 = 0
for a, b in zip(nparray1, nparray2):
    flavor4 += a * b
print(flavor4)

38
38
38
38


In [22]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4]))
norm2 = np.dot([1, 2], [3, 4])
print(norm1, '=', norm2 )

11 = 11


In [23]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
sumByCols = np.sum(nparray2, axis=0)
sumByRows = np.sum(nparray2, axis=1) 
print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


In [24]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
mean = np.mean(nparray2)
meanByCols = np.mean(nparray2, axis=0)
meanByRows = np.mean(nparray2, axis=1)

print('Matrix mean: ')
print(mean)
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows)

Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


In [25]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]])
nparrayCentered = nparray2 - np.mean(nparray2, axis=0)

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)
print('New mean by column')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


In [26]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]])
nparrayCentered = nparray2.T - np.mean(nparray2, axis=1) # Remove the mean for each row
nparrayCentered = nparrayCentered.T # Transpose back the result

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)
print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]
