In [ ]:
import numpy as np

In [ ]:
alist = [1, 2, 3, 4, 5]
narray = np.array([1, 2, 3, 4])

In [ ]:
print(alist)
print(narray)
print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(narray + narray)
print(alist + alist)

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
print(narray * 3)
print(alist * 3)

[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
npmatrix1 = np.array([narray, narray, narray]) # Matrix initialized with NumPy arrays
npmatrix2 = np.array([alist, alist, alist]) # Matrix initialized with lists
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray]) # Matrix initialized with both types
print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [ ]:
okmatrix = np.array([[1, 2], [3, 4]])
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [ ]:
badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]])
print(badmatrix)
print(badmatrix * 2)

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


C:\Users\dell\AppData\Local\Temp/ipykernel_13932/2051504424.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]])


In [ ]:
result = okmatrix * 2 + 1
print(result)

[[3 5]
 [7 9]]


In [ ]:
result1 = okmatrix + okmatrix
print(result1)
result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [ ]:
result = okmatrix * okmatrix
print(result)

[[ 1  4]
 [ 9 16]]


In [ ]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]])
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


In [ ]:
nparray = np.array([1, 2, 3, 4]) # Define an array
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[1 2 3 4]
Transposed array
[1 2 3 4]


In [ ]:
nparray = np.array([[1, 2, 3, 4]])
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


In [ ]:
nparray1 = np.array([1, 2, 3, 4])
norm1 = np.linalg.norm(nparray1)
nparray2 = np.array([[1, 2], [3, 4]])
norm2 = np.linalg.norm(nparray2)
print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


In [ ]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]])
normByCols = np.linalg.norm(nparray2, axis=0)
normByRows = np.linalg.norm(nparray2, axis=1)
print(normByCols)
print(normByRows)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [ ]:
nparray1 = np.array([0, 1, 2, 3]) # Define an array
nparray2 = np.array([4, 5, 6, 7]) # Define an array
flavor1 = np.dot(nparray1, nparray2) # Way-1
print(flavor1)
flavor2 = np.sum(nparray1 * nparray2) # Way-2
print(flavor2)
flavor3 = nparray1 @ nparray2 # Way-3
print(flavor3)
# As you never should do: #Way-4
flavor4 = 0
for a, b in zip(nparray1, nparray2):
    flavor4 += a * b
print(flavor4)

38
38
38
38


In [ ]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4]))
norm2 = np.dot([1, 2], [3, 4])
print(norm1, '=', norm2 )

11 = 11


In [ ]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
sumByCols = np.sum(nparray2, axis=0)
sumByRows = np.sum(nparray2, axis=1) 
print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


In [ ]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
mean = np.mean(nparray2)
meanByCols = np.mean(nparray2, axis=0)
meanByRows = np.mean(nparray2, axis=1)

print('Matrix mean: ')
print(mean)
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows)

Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


In [ ]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]])
nparrayCentered = nparray2 - np.mean(nparray2, axis=0)

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)
print('New mean by column')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


In [ ]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]])
nparrayCentered = nparray2.T - np.mean(nparray2, axis=1) # Remove the mean for each row
nparrayCentered = nparrayCentered.T # Transpose back the result

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)
print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]


In [ ]:
# importing modules
import numpy as np
import pandas as pd

In [ ]:
# creating and printing two matrics
arr1 = np.array([[5, 9, 3],[3, 7, 5]])
print(arr1)
arr2 = np.array([[3,-9],[5, 4],[7, -8]])
print(arr2)

[[5 9 3]
 [3 7 5]]
[[ 3 -9]
 [ 5  4]
 [ 7 -8]]


In [ ]:

# showing how to randomly initialize an array
print(np.random.rand(3, 4))

[[0.09533634 0.1649698  0.3048844  0.94518808]
 [0.19611831 0.78524805 0.19237293 0.63820579]
 [0.22616852 0.28415551 0.46618918 0.8766631 ]]


In [ ]:

# showing how to perform matrix multiplication
print(np.dot(arr1, arr2))

[[ 81 -33]
 [ 79 -39]]


In [ ]:

# showing how to perform element-wise matrix multiplication
res = [[0 for x in range(len(arr1))] for y in range(len(arr2[0]))]

In [ ]:

for i in range(len(arr1)): 
  for j in range(len(arr2[0])): 
    for k in range(len(arr2)): 
      res[i][j] += arr1[i][k] * arr2[k][j]
 
print (res)

[[81, -33], [79, -39]]


In [ ]:

# showing how to find the mean of the first matrix
mean = np.mean(arr1)
print(mean)

5.333333333333333


In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [3]:
import numpy as np
import pandas as pd

In [4]:
main_data = pd.read_csv("/content/drive/MyDrive/csv/mtcars.csv")
del main_data['model']


In [5]:

# shwing the meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
